import type { Metadata } from "next";

import { AppProviders } from "./providers";

import "./globals.css";

export const metadata: Metadata = {
  title: "NeuroNote",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <html lang="en" suppressHydrationWarning>
          <body>
            <AppProviders>{children}</AppProviders>
          </body>
        </html>
      </body>
    </html>
  );
}
